service: bitlambda

app: bitwalla
org: faithful

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-1
  # uncomment org variable if you are using sls dashboard
  # org: faithful

  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:bitlambda-dev-SNSTopic

custom:
  snsTopic: '${self:service}-${self:provider.stage}-SNSTopic'
  stage: '${opt:stage, self:provider.stage}'

# functions

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  getBlocks:
    handler: blocks.blockList
    events:
      - http:
          path: blocks
          method: get
          cors: true

  snsLambdaTriggered:
    handler: blocks.snsLambdaTriggered
    events:
      - sns: ${self:custom.snsTopic}
